### ISSUE TITLE
subtree로 관리 

### ISSUE THREAD

**Issue by jaeyeonling** [juyoungyoo/NextStep-TDD#1]
하나의 저장소에서 여러 저장소를 관리하기 위해 git subtree라는 기능이 있습니다.

현재 프로젝트를 직접 옮겨둔 구조에서 프로젝트의 변경사항이 있으면(있을리는 없지만) 한땀한땀 수정해야하는 일이 생길 수 있지 않을까요?

그리고 실제 하위 프로젝트로 가서 보는게 커밋 히스토리와 풀리퀘 히스토리도 볼 수 있어서 더 좋아보이네요!

관련 링크 첨부합니다.

https://homoefficio.github.io/2015/07/18/git-subtree/

**Comment by juyoungyoo** [comment]
감사합니다 :) 
참고해볼게요
